### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by XenGi** [AppImage/AppImageUpdate#166] opened 2021-01-09 00:12 UTC
The app doesn't start. No idea why.
```
$ ./AppImageUpdate-x86_64.AppImage 
AppImageUpdate version 1-alpha (commit 1f52c72), build 21 built on 2020-12-13 07:19:11 UTC

(AppRun.wrapped:179591): Gtk-WARNING **: 01:09:14.976: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
fish: “./AppImageUpdate-x86_64.AppImage” terminated by signal SIGABRT (Abort)
```

Came here because FreeCAD wiki told me to use AppImageUpdate. FreeCAD starts but the GUI is broken. Now this AppImageUpdate doesn't even start and gives me GTK errors.

**Comment by TheAssassin** [comment] 2021-01-09 00:14
Provide more information, at least what OS you use (including exact version!). We can't guess.

**Comment by probonopd** [comment] 2021-01-09 12:24
Duplicate of #150

**Closed by probonopd** 2021-01-09 12:24 UTC

**Comment by probonopd** [comment] 2022-05-21 08:21
Please retry with https://github.com/AppImage/AppImageUpdate/releases/tag/continuous.
