### ISSUE TITLE
Program could not find or load xcb

### ISSUE THREAD

**Issue by Noammac** [AppImage/AppImageUpdate#85] opened 2018-03-29 22:20 UTC
Since I downloaded the AppImage I was unable to run it due to an odd error with the following message:

```
AppImageUpdate version 1-alpha (commit 99155ab), build 291 built on 2018-03-29 21:41:05 UTC
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
[1]    24026 abort (core dumped)  ./AppImageUpdate-291-99155ab-x86_64.AppImage
```

I tried to run it with `QT_DEBUG_PLUGINS=1` prefixing it in order to see where the problem originates and got a message as follows:

```
AppImageUpdate version 1-alpha (commit 99155ab), build 291 built on 2018-03-29 21:41:05 UTC
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_AppImaDInCfQ/usr/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_AppImaDInCfQ/usr/plugins/platforms/libqxcb.so"
Found metadata in lib /tmp/.mount_AppImaDInCfQ/usr/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329987
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_AppImaDInCfQ/usr/bin/platforms" ...
Cannot load library /tmp/.mount_AppImaDInCfQ/usr/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)
QLibraryPrivate::loadPlugin failed on "/tmp/.mount_AppImaDInCfQ/usr/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_AppImaDInCfQ/usr/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
[1]    24540 abort (core dumped)  QT_DEBUG_PLUGINS=1 ./AppImageUpdate-291-99155ab-x86_64.AppImage
```

So, following some advice I found on the internet, I decided to extract the AppImage, go to `usr/lib`, remove `libfreetype.so.6` and then try to execute AppRun. It worked.

I'm running Antergos Linux with the most updated packages (did a full system update and then restarted just in case). No idea what causes this.

**Comment by TheAssassin** [comment] 2018-03-29 22:34
Arch and its derivatives recently broke the backwards compatibility of libfontconfig, therefore AppImages depending on the library will show strange behavior or even refuse to work entirely.

Duplicate of https://github.com/probonopd/linuxdeployqt/issues/259 and https://github.com/probonopd/linuxdeployqt/issues/261. Please subscribe to those issues instead.

There is nothing we could do about this issue, at least not here in the repository. Please tell the maintainers of these so-called "distros" to stop being annoying for packagers. They break the backwards compatibility of some core libraries every couple of weeks...

**Comment by TheAssassin** [comment] 2018-03-29 22:34
I think I will keep this issue open until we have a solution, though, although I don't see what we could do about it.

**Comment by probonopd** [comment] 2018-03-30 07:06
> I don't see what we could do about it.

We should find or create tickets in libfontconfig and Arch, and describe the issue and its effects (e.g., by linking to tickets resulting from this).

**Comment by probonopd** [comment] 2018-03-30 07:09
Looks like no one has even reported that there is an issue so far:

* https://bugs.archlinux.org/index.php?string=FT_Done_MM_Var - no results
* https://bugs.freedesktop.org/buglist.cgi?quicksearch=FT_Done_MM_Var - no results

**Comment by TheAssassin** [comment] 2018-03-30 09:54
@probonopd what I meant was, specifically for AppImageUpdate. That's why I posted the links to the upstream bugs in linuxdeployqt.

**Comment by ackalker** [comment] 2018-05-08 16:41
I'm seeing a very similar issue on Void Linux (x86_64, glibc) when I try to run the Subsurface demo app downloaded straight from the homepage.
From another angle (using `LD_DEBUG=libs`) I discovered the underlying error:
```
/usr/lib/libfontconfig.so.1: error: symbol lookup error: undefined symbol: FT_Done_MM_Var (fatal)
```

I think that blaming distro's for not being backwards compatible is a bit disingenuous. Isn't AppImage supposed to be a solution to dependency troubles like this (by bundling the dependencies along with the app) instead of pushing them down one more level of indirection?

**Comment by antony-jr** [comment] 2018-05-08 17:07
> I think that blaming distros for not being backwards compatible is a bit disingenuous, considering that AppImage claims to be a solution to dependency troubles like this (by bundling the dependencies along with the app). Instead it appears to just push dependency hell down one more level of indirection.

@ackalker AppImages are simply **bundles** and its all upto the **application developer** to make it good. But **Thank You** for the point out , I hope this gets fixed soon ( Feel free to give a **PR**). 
AppImageUpdate **works great** in my **rolling distro**(Manjaro Linux). So I think not all arch linux derivatives are affected.

**Comment by ackalker** [comment] 2018-05-08 17:13
@antony-jr Thanks for your quick reply.
I will certainly keep an eye out for updates on AppImage, as I like the idea. I felt the need to comment because hitting a dependency problem right off the bat trying to run the showcase app on the homepage could be a major turnoff.

**Comment by ackalker** [comment] 2018-05-08 17:37
@TheAssassin Thanks for the insigt! I'm most certainly interested in helping out with testing, time permitting.

**Comment by TheAssassin** [comment] 2018-05-08 18:06
@probonopd I think we can close this issue now that we have libfontconfig and friends in the excludelist, can't we?

**Comment by Noammac** [comment] 2018-05-09 17:55
Confirmed.

**Comment by probonopd** [comment] 2018-05-09 17:57
Thank you!

**Closed by probonopd** 2018-05-09 17:57 UTC
Labels: bug, duplicate
