### ISSUE TITLE
FLTK does not scale on HiDPI systems

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#52] opened 2017-12-03 00:39 UTC
![screenshot from 2017-12-03 01-38-50](https://user-images.githubusercontent.com/2480569/33521172-77e4c686-d7c2-11e7-8f84-20a101ec89d8.png)

**Comment by TheAssassin** [comment] 2017-12-03 01:14
Right, that's a problem. FLTK seems to be pixel based and doesn't have any HiDPI supporting API. But as it doesn't really affect the usability, I'll flag it as low priority for now. The next sprint isn't about AppImageUpdate anyway, and we have 14 other issues that need some time.

**Comment by TheAssassin** [comment] 2018-02-23 11:51
@probonopd would you try the Qt UI, please? I could imagine it works as intended. If that's the case, we could consider ceasing development of the FLTK UI in favor of the Qt version, once we consider it stable.

**Comment by probonopd** [comment] 2018-02-23 17:48
Agree, things like HiDPI should be easier to support using Qt than with FLTK. Hence closing here. (Not on my HiDPI machine at the moment, will reopen if the issue persists there.)

**Comment by TheAssassin** [comment] 2018-02-23 18:44
Reopening to keep track of the whole story. We can close this once the FLTK UI has been depracated.

**Comment by TheAssassin** [comment] 2018-03-13 23:28
Closed by #81.

**Closed by TheAssassin** 2018-03-13 23:28 UTC
Labels: deprioritized, ux
