### ISSUE TITLE
Does not handle partially downloaded files correctly

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#21] opened 2017-10-30 15:25 UTC
```
me@host:~$ dd if=Downloads/OpenSCAD-Nightly-0-Build1967.1.glibc2.14-x86_64.AppImage of=partial.AppImage bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00188044 s, 558 MB/s
```

__Expected result:__

Downloads the rest of the file.

__Actual result:__

When trying to update this with `AppImageUpdate-x86_64.AppImage` via the __GUI__:

![screenshot from 2017-10-30 16-23-14](https://user-images.githubusercontent.com/2480569/32179076-ad66f5de-bd8e-11e7-952a-44629ef02257.png)

Of course, running this fails:

![screenshot from 2017-10-30 16-25-44](https://user-images.githubusercontent.com/2480569/32179189-06f7c754-bd8f-11e7-8cb0-6036707060ef.png)

When trying to update the same partial AppImage via the __CLI__ using the same `AppImageUpdate-x86_64.AppImage`:

```
me@host:~$ Downloads/AppImageUpdate-x86_64.AppImage partial.AppImage 
Checking for updates...
Parsing failed! Are you sure the file is an AppImage?
```

**Comment by TheAssassin** [comment] 2017-10-30 17:58
Well, accidentally breaking an AppImage is not really something that will occur _that_ often. ZSync2 for example won't ever create this kind of broken AppImage.

The actually interesting bit here is that AppImageUpdate reports this AppImage as being up to date, although the file should've been hashed using SHA-1 and compared to the hash in the `.zsync` file. That is the actual bug here.

**Comment by probonopd** [comment] 2017-10-30 18:04
If I am not totally mistaken, then the original `zsync` and `zsync-curl` can handle this kind of situation.

**Comment by TheAssassin** [comment] 2017-10-30 19:26
ZSync2 is capable of this as well, and this bug should've never happened, so I assume there might be a bug in the implementation of `zsync_sha1` that I'll have to track down.

**Comment by TheAssassin** [comment] 2017-11-03 13:53
The bug was caused by AppImageUpdate not passing the real path to the ZSync2 client. The update check then passed an empty string to libzsync, which thought the verification was successful.

Initially I thought the update check might be wrong because when the `.zsync` file is downloaded, the update check would automatically use the `Filename:` from there, but this wasn't happening.

I fixed this issue by passing the real path to the AppImage to the ZSync2 client the update check instantiates in commit https://github.com/AppImage/AppImageUpdate/commit/47b2e7c637499d2e9557786896ee3cbf2fc5cdb4. Also, I added a lot more error handling to make sure this won't happen again in zsync2 in commit https://github.com/TheAssassin/zsync2/commit/f61d8ac9f92b741311298bf58997fac7797a03ef.

My own tests showed that everything works fine now, therefore I'm closing this issue. @probonopd please check again with a recent build. Feel free to reopen the issue in case you find further problems. Closing https://github.com/TheAssassin/zsync2/issues/8 as well.

**Comment by probonopd** [comment] 2017-11-03 15:00
Still getting errors:

```
me@host:~$ wget -c "https://download.opensuse.org/repositories/home:/nandub:/MyAppImages/AppImage/aria2-latest-x86_64.AppImage"
me@host:~$ dd if=Downloads/aria2-1.24.0-1.1.Build12.15.glibc2.17-x86_64.AppImage of=aria.AppImage bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00165525 s, 633 MB/s
me@host:~$ Downloads/AppImageUpdate-x86_64.AppImage aria.AppImage 
AppImageUpdate version 1-alpha (commit 2a677f0), build 107 built on 2017-11-02 22:42:06 UTC
Checking for updates...
Parsing failed! Are you sure the file is an AppImage?
```

**Comment by TheAssassin** [comment] 2017-11-03 15:58
With my local dev build, parsing worked perfectly fine, and the update started. With the latest build from GitHub releases, parsing failed once, but a second run finished the AppImage download. Please try to call AppImageUpdate a second time.

**Comment by TheAssassin** [comment] 2017-11-03 16:00
I retried calling the dd command a few times (> 5), every single time, updating worked fine. I'm not sure what the issue is, but I can't reproduce it any more. Closing therefore.

**Closed by TheAssassin** 2017-11-03 16:00 UTC
Labels: bug
