### ISSUE TITLE
AppImageUpdate-Qt `--version` wants an X display

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageUpdate#71] opened 2018-02-20 17:48 UTC
When running `'--version'` with AppImageUpdate-Qt I see the following issues:

* **Build 208:** `AppImageUpdate-Qt-208-012801f-x86_64.AppImage --version` on a local machine returns this line:

         AppImageUpdate-Qt version 1-alpha (commit 012801f), build 208 built on 2018-02-15 21:55:43 UTC

    This command does not use any GUI dialog to pop up, but it wants an X display to be present. Because the same command, when run via an SSH remote login returns this:    

        AppImageUpdate-Qt version 1-alpha (commit 012801f), build 208 built on 2018-02-15 21:55:43 UTC
        qt.qpa.screen: QXcbConnection: Could not connect to display
        Could not connect to any X display.

    So while it DOES give the required info through SSH as well, it still is ugly and does not feel right...

----

*  **Build 212:** `AppImageUpdate-Qt-212-9c3a6d6-x86_64.AppImage --version` does not work at all:

        execv error: No such file or directory

<sup>Note: the application itself seems to work just fine (though I didn't do any actual updates with it yet...).</sup>

**Comment by antony-jr** [comment] 2018-02-20 18:32
duplicate of https://github.com/AppImage/AppImageUpdate/issues/70

**Comment by TheAssassin** [comment] 2018-02-20 18:32
Thanks for your notice, @antony-jr. I was about to close it as a duplicate. Please refer to #70, @KurtPfeifle.

**Comment by TheAssassin** [comment] 2018-02-20 19:07
I just discovered there's a second aspect in this issue that needs some answer.

I agree that the `--version` flag shouldn't require a UI. I am not a Qt expert, and I'll try to find out whether I can change the workflow in the code a bit so that there's no UI required for the CLI parsing.

**Comment by KurtPfeifle** [comment] 2018-02-20 23:40
I thought my chosen headline was indicating what I regarded as the FIRST aspect of this issue. The other thing (*"execv error:..."*) I only found when I was looking for an more uptodate version to verify what I first had seen with build 208...

**Comment by antony-jr** [comment] 2018-02-21 02:57
@TheAssassin The AppImageUpdate-Qt*.AppImage is for GUI , right ?
There is a appimageupdate-*.AppImage for CLI usage , Then it is good to check for X Server when using AppImageUpdate-Qt*.AppImage eventhough its just a version check. Am I wrong @KurtPfeifle ?

**Comment by TheAssassin** [comment] 2018-02-21 02:59
Yes, @antony-jr. But anyway, I do think any app shouldn't require an X server for non-UI work like displaying its version.

Also, nobody's explicitly checking for an X server. It's the Qt framework that implicitly checks for that. I'm interested in finding out the cause and fixing it.

**Comment by antony-jr** [comment] 2018-02-21 03:11
@TheAssassin You can not do it qt , this is what happens when you force qt to compile.

```
QWidget: Cannot create a QWidget without QApplication
Aborted (core dumped)
```

QApplication always pulls the required resources when called. ( Like X Server ). **The Workaround**  is to use some **custom command line parsing to exit the main function** before you call ``` QApplication::QApplication(int argc ,const char **argv); ```

From Qt Docs... 

> For any GUI application using Qt, there is precisely one QApplication object, no matter whether the application has 0, 1, 2 or more windows at any given time. For non-QWidget based Qt applications, use QGuiApplication instead, as it does not depend on the QtWidgets library.

 > Some GUI applications provide a special batch mode ie. provide command line arguments for executing tasks without manual intervention. In such non-GUI mode, it is often sufficient to instantiate a plain QCoreApplication to avoid unnecessarily initializing resources needed for a graphical user interface.

**Comment by TheAssassin** [comment] 2018-02-21 03:13
Thanks for your explanation. That was my guess, too. However, I'm not working on this with priority, as it isn't really preventing anyone from using the application.
IIRC you can use `QCommandLineParser without a `QApplication`. We'll have to see whether it's worth it to make these changes, though.

**Comment by antony-jr** [comment] 2018-02-21 03:19
> IIRC you can use QCommandLineParser without a QApplication

Yes thats true. @TheAssassin

**Comment by KurtPfeifle** [comment] 2018-02-21 16:59
@antony-jr:

> *"[....] its just a version check. Am I wrong @KurtPfeifle ?"*

If I remember correctly, last I checked, almost ***ALL*** KDE and many Qt GUI applications could be run with certain CLI params (like *`'--help'`*, *`'--help-kde'`*, *`'--version'`*)  which do not need an X server and which do not complain if an X server is missing and which print the requested info just to *`<stdout>`*...

One example of an AppImage which does not require an X server: my version of *OpenSCAD* which simply prints *`'OpenSCAD version 2018.01.13'`* into the terminal for *`'--version'`*, and a little help screen for *`'--help'`*.

Another example is LibreOffice: the AppImages there print a quite long output for *`'--help'`* and a one-line version string for *`'--version`*.

So my expectation regarding this topic isn't very exotic... I do not consider this issue to be very important, though. As my initial comment said, for me it just *'is ugly and does not feel right...'*

**Comment by antony-jr** [comment] 2018-02-22 05:00
>  for me it just 'is ugly and does not feel right...'

@KurtPfeifle  I Agree because the code is just in beta level , But I think @TheAssassin can fix this anytime. No need to rush. :+1:

**Closed** 2018-02-23 22:18 UTC
Labels: duplicate
