### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#142] opened 2020-02-17 18:53 UTC
Build fails; I retriggered Travis but it still fails.

**Comment by TheAssassin** [comment] 2020-02-18 04:00
Next time please look into the log at least. "Build fails" is, retrospectively, a quite useless issue description, as the future "us" cannot tell what actually broke, nor which build the issue was related to at all.

Failing job: https://travis-ci.org/AppImage/AppImageUpdate/jobs/633677316

Breakage: https://travis-ci.org/AppImage/AppImageUpdate/jobs/633677316#L1161

Seems we have to fix some icon naming in some build script. Shouldn't be too difficult.

**Comment by TheAssassin** [comment] 2020-02-18 04:09
The build failure is caused by b468b3d56cdcdbba46b9603994502021b906bfa4 and its predecessor. @probonopd you have correctly changed the build script, and the icon file is properly bundled by linuxdeploy. However, you would've had to update the desktop file as well. It still contains the old `Icon=` entry.

I'm going to fix this now...

**Comment by TheAssassin** [comment] 2020-02-18 04:18
Fixed by https://github.com/AppImage/AppImageUpdate/commit/3516485d75aa46aaf7f618fac2e511ce86e6c5ab.

**Closed by TheAssassin** 2020-02-18 04:18 UTC
