### ISSUE TITLE
Gtk:ERROR when trying to start

### ISSUE THREAD

**Issue by phw** [AppImage/AppImageUpdate#145] opened 2020-03-17 13:29 UTC
Starting the latest AppImageUpdate-x86_64.AppImage results in:

```
$ ./AppImageUpdate-x86_64.AppImage                          
AppImageUpdate version 1-alpha (commit ea07e03), build 429 built on 2020-03-04 14:06:40 UTC

(AppRun.wrapped:108381): Gtk-WARNING **: 14:26:59.210: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Schwerer Fehler beim Lesen einer PNG-Bilddatei: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Schwerer Fehler beim Lesen einer PNG-Bilddatei: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
zsh: abort (core dumped)  ./AppImageUpdate-x86_64.AppImage
```

Arch Linux with GNOME 3.36. The icon `/usr/share/icons/Adwaita/16x16/status/image-missing.png` exists.

**Comment by probonopd** [comment] 2020-03-17 19:15
What happens if you do:

```
./AppImageUpdate-x86_64.AppImage --appimage-extract
rm squashfs-root/usr/plugins/platformthemes/*
./squashfs-root/AppRun
```

**Comment by phw** [comment] 2020-03-18 08:15
Removing `squashfs-root/usr/plugins/platformthemes/*` works. Only uncommenting `export QT_QPA_PLATFORMTHEME=gtk3` has no effect.

I had previously a version that was working, it identifies as:

    AppImageUpdate version 1-alpha (commit e17e350), build 422 built on 2019-10-13 13:17:11 UTC

The version crashing is:

    AppImageUpdate version 1-alpha (commit ea07e03), build 429 built on 2020-03-04 14:06:40 UTC

The one from  https://github.com/antony-jr/AppImageUpdater/releases/tag/continuous works, but that's a different tool, right?

**Comment by nlordell** [comment] 2020-03-19 11:48
Might be related to this https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1838891

> I just managed to reproduce the crash locally. Just before the crash, the following lines are printed to stderr:
> 
> (AppImageLauncherSettings:27871): Gtk-WARNING **: 21:45:01.935: Could not load a pixbuf from icon theme.
> This may indicate that pixbuf loaders or the mime database could not be found.
> **
> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image > file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
> 
> I think most important part here is “bad parameters to zlib”. AppImageLauncher uses its own static zlib (lib/AppImageUpdate/lib/zsync2/lib/zlib/libzsync2_libz.a) which is incompatible with public zlib (/lib/x86_64-linux-gnu/libz.so.1) that GTK was compiled against.
> 
> Recompiling AppImageLauncher with system zlib should help, but I haven’t found a way to do that. I suggest you to ask AppImageLauncher developer about that.
> 
> Attaching a stacktrace for future reference.

**Comment by probonopd** [comment] 2020-03-21 08:42
@TheAssassin given the above I think it would be a good idea not to ship platformthemes for now, wdyt?

**Comment by TheAssassin** [comment] 2020-04-02 18:52
You were the one to urge for including this platform theme stuff. It's not really documented, IIRC it was some random git repo you found, right?

We don't use the upstream Ubuntu binaries IIRC, but use Stephan Binner's PPA. Perhaps you should contact him and ask about the issues?

**Comment by probonopd** [comment] 2020-04-04 09:47
What is `libzsync2_libz` and why is it needed? Could it be conflicting the normal libz?

**Comment by mfilipe** [comment] 2020-04-11 02:03
Fedora 31

```
AppImageUpdate version 1-alpha (commit cb611d8), build 431 built on 2020-04-07 21:47:19 UTC
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
 
(AppRun.wrapped:16448): Gtk-WARNING **: 22:45:35.230: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
```

**Comment by vasyugan** [comment] 2020-11-02 14:50
I should say that I see the same on Debian Buster with MATE.

**Comment by probonopd** [comment] 2020-12-28 19:46
Duplicate of https://github.com/AppImage/AppImageUpdate/issues/150, workaround in https://github.com/AppImage/AppImageUpdate/issues/150#issuecomment-674013820.

**Closed by probonopd** 2020-12-28 19:46 UTC

**Comment by probonopd** [comment] 2022-05-21 08:20
Please retry with https://github.com/AppImage/AppImageUpdate/releases/tag/continuous.
