### ISSUE TITLE
Direct links to the most update AppImageUpdate and appimageupdatetool

### ISSUE THREAD

**Issue by luzpaz** [AppImage/AppImageUpdate#105] opened 2018-11-11 13:41 UTC
Is there a way to make a link to the most up to date AppImageUpdate and AppImageUpdateTool ? 

Something similiar to `https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage` ?

**Comment by probonopd** [comment] 2018-11-11 13:51
`curl -s https://api.github.com/repos/AppImage/AppImageUpdate/releases | grep browser_download_url | grep x86_64.AppImage | grep AppImageUpdate- | grep -v zsync | cut -d'"' -f4` should do.

**Comment by probonopd** [comment] 2018-11-11 13:51
Similarly, `curl -s https://api.github.com/repos/AppImage/AppImageUpdate/releases | grep browser_download_url | grep x86_64.AppImage | grep appimageupdatetool | grep -v zsync | cut -d'"' -f4`

**Comment by luzpaz** [comment] 2018-11-11 14:11
@probonopd I'm creating a page over at https://www.freecadweb.org/wiki/Appimage
and I was hoping to get a direct link, it's less confusing if I don't add the above bash wizardry. Thanks, nevertheless.

**Comment by TheAssassin** [comment] 2018-11-11 14:12
Next time, please describe your use case a bit more detailedly. You're not the first one requesting static filenames for this tool.

**Comment by luzpaz** [comment] 2018-11-11 16:00
I will. I try but sometimes, I can't think of the correct jargon.

**Comment by probonopd** [comment] 2018-11-11 16:04
Giving some background ("I would like ... to do ... because ...) usually helps :+1:

**Comment by TheAssassin** [comment] 2018-11-11 16:40
Closing as duplicate of #89.

**Closed by TheAssassin** 2018-11-11 16:40 UTC
