### ISSUE TITLE
[rewrite] Segfault when appimageupdategui-x86_64.AppImage tries to update itself

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#17] opened 2017-10-28 08:48 UTC
```
me@host:~$ wget https://transfer.sh/Kljvv/appimageupdategui-x86_64.AppImage
me@host:~$ chmod a+x appimageupdategui-x86_64.AppImage
me@host:~$ /appimageupdategui-x86_64.AppImage appimageupdategui-x86_64.AppImage 
Checking for updates...
Speicherzugriffsfehler
```

**Comment by TheAssassin** [comment] 2017-10-28 10:44
You should know where the bug comes from. It's because of the broken cURL that is bundled at the moment. Hence closing as duplicate of https://github.com/TheAssassin/zsync2/issues/4.

**Closed by TheAssassin** 2017-10-28 10:44 UTC
Labels: duplicate

**Comment by TheAssassin** [comment] 2017-10-28 10:58
That said, you can try to un-bundle libcurl, libssl etc. from the AppImage you download as a workaround.

**Comment by TheAssassin** [comment] 2017-10-28 11:27
Confirming that this works, just delete `usr/lib/libcurl-gnutls.so.4` and the application will work as intended.
