### ISSUE TITLE
Updating AppImageUpdate with itself does not work as expected

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#28] opened 2017-10-30 21:59 UTC
Self-updating AppImageUpdate does not work as expected when using an older version of AppImgageUpdate (from earlier today) - I can see there is a newer pre-release available on GitHub Releases (since 26 minutes or so).

The update information inside this AppImage is `gh-releases-zsync|AppImage|AppImageUpdate|continuous|AppImageUpdate-*x86_64.AppImage.zsync`

![deepinbildschirmfoto20171030225721](https://user-images.githubusercontent.com/2480569/32197769-c4efeec2-bdc5-11e7-935f-ecefb2d2d51c.png)

**Comment by TheAssassin** [comment] 2017-10-30 22:07
Well, initially you suggested to look for updates only on errors. That's what's implemented. I don't see the bug here, the self update is not triggered at all, everything works as intended.

**Comment by TheAssassin** [comment] 2017-10-30 22:09
Feel free to reopen if you think this behavior should change.

**Comment by probonopd** [comment] 2017-10-30 22:11
...yes but I believe this AppImage is _not_ up to date. Is it?

```
me@host:~$ sha1sum '/home/me/Downloads/AppImageUpdate-x86_64 (1).AppImage'
f5f61a352bd7edd8984464c010cd3b1981537c69  /home/me/Downloads/AppImageUpdate-x86_64 (1).AppImage
```

**Comment by TheAssassin** [comment] 2017-10-30 22:12
Ok, I think I misunderstood your request.

**Comment by probonopd** [comment] 2017-10-30 22:14
Right, the current one (as of now) has `d978f47d348054ad6cfb35e5e8f1cd8f26c49c3a`

**Comment by TheAssassin** [comment] 2017-10-30 22:20
I adjusted the title, and would ask you to take care not to use the words "self" and "update" in the same context like this to avoid ambiguous situations like this. I thought of AppImageSelfUpdate, which is implemented in AppImageUpdate AppImages, serving as a kind of reference implementation.

**Comment by probonopd** [comment] 2017-10-30 22:21
Ah ok. Thanks for looking into this.

**Comment by probonopd** [comment] 2017-10-30 22:24
[AppImageUpdate-x86_64 (1).AppImage.zip](https://github.com/AppImage/AppImageUpdate/files/1428995/AppImageUpdate-x86_64.1.AppImage.zip)

Maybe helpful to reproduce this. Zipped for GitHub Issues.

**Comment by TheAssassin** [comment] 2017-11-02 22:51
Turned out the update check had a few minor flaws (fixed in https://github.com/TheAssassin/zsync2/commit/f61d8ac9f92b741311298bf58997fac7797a03ef).

Another issue occurred due to libzsync not being able to resolve redirections of URLs. To fix that behaviour, I'm using a `HEAD` request to resolve the final URL before passing it to libzsync, which seems to have solved the issue. See https://github.com/TheAssassin/zsync2/commit/af6aab80a18c8ed15ca36c9a92141e40918d0085.

I'm closing this, but would ask you to verify that it works now.

**Closed** 2017-11-02 22:51 UTC
Labels: invalid
