### ISSUE TITLE
Could not start on fedora 33

### ISSUE THREAD

**Issue by mildred** [AppImage/AppImageUpdate#161] opened 2020-12-08 13:21 UTC
On start with fedora 33, AppImageUpdate crashes with:

```
$ LC_ALL=C AppImageUpdate-x86_64.AppImage
AppImageUpdate version 1-alpha (commit cb611d8), build 431 built on 2020-04-07 21:47:19 UTC
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(AppRun.wrapped:43588): Gtk-WARNING **: 14:19:59.328: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
zsh: IOT instruction (core dumped)  LC_ALL=C AppImageUpdate-x86_64.AppImage
```

**Comment by mayonezo** [comment] 2020-12-28 19:40
Same for Debian Buster:

AppImageUpdate version 1-alpha (commit 1f52c72), build 21 built on 2020-12-13 07:19:11 UTC

(AppRun.wrapped:20585): Gtk-WARNING **: 20:35:30.731: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
Aborted

**Comment by probonopd** [comment] 2020-12-28 19:44
Seems to be a duplicate of https://github.com/AppImage/AppImageUpdate/issues/150.

**Closed by probonopd** 2020-12-28 19:44 UTC
